# Generated by Django 4.0.4 on 2022-06-11 08:10

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_comment_options_comment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='available',
        ),
        migrations.AddField(
            model_name='tour',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 14, 10, 9, 895486)),
            preserve_default=False,
        ),
    ]
