# Generated by Django 4.0.5 on 2022-06-13 05:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0003_remove_tour_available_tour_end_date_tour_start_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('tour', 'user')},
        ),
    ]
