# Generated by Django 4.0.5 on 2022-06-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_saved_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_view',
            field=models.IntegerField(default=0),
        ),
    ]
