# Generated by Django 4.0.5 on 2022-06-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_tour_tour_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='tour_view',
        ),
    ]
