# Generated by Django 4.0.5 on 2022-06-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_rename_userhistory_tourhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourhistory',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
